version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: skypanel_app
    restart: always
    ports:
      - "3333:3333"
    env_file:
      - ./.env
    volumes:
      - .:/app
      - /app/node_modules

