name: GitHub Copilot Setup

on:
  push:
    branches: [ main, development ]
    paths:
      - '.github/copilot/**'
      - '.github/GITHUB_COPILOT.md'
      - 'COPILOT.md'
  workflow_dispatch:

jobs:
  update-copilot-configuration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Validate Copilot configuration
        run: |
          if [ -f ".github/copilot/configuration.yml" ]; then
            echo "✅ Copilot configuration file exists"
            # Add validation if needed
          else
            echo "❌ Copilot configuration file not found"
            exit 1
          fi
          
      - name: Notify about update
        run: |
          echo "GitHub Copilot configuration has been updated."
          echo "Configuration location: .github/copilot/configuration.yml"
          echo "Documentation: .github/GITHUB_COPILOT.md and COPILOT.md"
